version: '2'

services:
    db:
        image: mariadb
        volumes:
            - ./data/mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    adminer:
        image: adminer
        restart: always
        ports:
          - 8081:8080

    php:
        image: salvatorecoluccia94/oifr_php
        build:
            context: .
            dockerfile: php7-fpm/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
            - ./symfony/var/sessions/dev:/var/www/symfony/var/sessions
        environment:
            SYMFONY_ENV: ${SYMFONY_ENV}
            SYMFONY_DEBUG: ${SYMFONY_DEBUG}
            XDEBUG_CONFIG: remote_host=192.168.42.15
    nginx:
        image: salvatorecoluccia94/oifr_nginx
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./tmp/nginx/:/var/tmp
        environment:
            SYMFONY_ENV: ${SYMFONY_ENV}
            SYMFONY_DEBUG: ${SYMFONY_DEBUG}
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx